project_name: gitleaks

builds:
  - main: ./main.go
    binary: gitleaks
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ldflags:
      - -s -w -X=github.com/AikidoSec/gitleaks/cmd.Version={{.Version}}
    env:
      - CGO_ENABLED=0
archives:
  - builds: [gitleaks]
    format_overrides:
      - goos: windows
        format: zip
